version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    command: npm start
